export type StructureClass = "tiled" | "nested" | "morphic" | "natural" | "random";

export interface Corpus {
  id: string;
  name: string;
  klass: StructureClass;
  blurb: string;
  text: string;
}

function fibWord(n: number): string {
  let a = "a";
  let b = "ab";
  if (n <= 0) return a;
  if (n === 1) return b;
  for (let i = 2; i <= n; i++) {
    const t = b + a;
    a = b;
    b = t;
  }
  return b;
}

function thueMorse(levels: number): string {
  let s = "0";
  for (let i = 0; i < levels; i++) {
    let next = "";
    for (const ch of s) next += ch === "0" ? "01" : "10";
    s = next;
  }
  return s;
}

function koch(levels: number): string {
  let s = "F";
  for (let i = 0; i < levels; i++) {
    let next = "";
    for (const ch of s) next += ch === "F" ? "F+F--F+F" : ch;
    s = next;
  }
  return s;
}

function lcg(seed: number, n: number, alphabet: string): string {
  let x = seed >>> 0;
  let out = "";
  for (let i = 0; i < n; i++) {
    x = (Math.imul(x, 1664525) + 1013904223) >>> 0;
    out += alphabet[x % alphabet.length];
  }
  return out;
}

const CODE_SNIPPET = `function density(n, g) {
  if (g === 0) return 0;
  return n / g;
}
function density(n, g) {
  if (g === 0) return 0;
  return n / g;
}
function density(n, g) {
  if (g === 0) return 0;
  return n / g;
}
`;

const ENGLISH = `A system's state does not need to contain its capacity. It only needs to contain enough to reconstruct the capacity it needs, at the moment it needs it. Capacity is not what the system retains. Capacity is what it can reconstruct from what it retains.`;

const RECORDS = `{"id":1,"role":"agent","ok":true}{"id":2,"role":"agent","ok":true}{"id":3,"role":"agent","ok":true}{"id":4,"role":"agent","ok":true}{"id":5,"role":"agent","ok":true}`;

const DNA = "ATGATGATGATGCCCATGATGATGATGTTATGATGATGATGCCCATGATGATGATG";

export const CORPORA: Corpus[] = [
  {
    id: "repeat",
    name: "Pure tile",
    klass: "tiled",
    blurb: "A short motif copied. Grammar compressors should jump in density.",
    text: "abcabcabcabcabcabcabcabcabcabcabcabc",
  },
  {
    id: "repair-wiki",
    name: "Re-Pair example",
    klass: "tiled",
    blurb: "The string from Larsson & Moffat’s illustration: two motifs, two scales.",
    text: "xabcabcy123123zabcabc",
  },
  {
    id: "nested",
    name: "Nested hierarchy",
    klass: "nested",
    blurb: "Phrases inside phrases. Sequitur’s home territory.",
    text: "aaabaaabaaabxyaaabaaabaaabxyaaabaaabaaab",
  },
  {
    id: "mississippi",
    name: "mississippi",
    klass: "tiled",
    blurb: "The classic running example for string algorithms.",
    text: "mississippi",
  },
  {
    id: "fibonacci",
    name: "Fibonacci word",
    klass: "morphic",
    blurb: "Generated by A → AB, B → A. Uniform morphic structure, no long tandem runs.",
    text: fibWord(9),
  },
  {
    id: "thue-morse",
    name: "Thue–Morse",
    klass: "morphic",
    blurb: "Overlap-free automatic sequence. Structure without obvious repeats of length > 2×.",
    text: thueMorse(6),
  },
  {
    id: "koch",
    name: "Koch axiom",
    klass: "morphic",
    blurb: "An L-system already expanded. The grammar that made it is smaller than the trace.",
    text: koch(3),
  },
  {
    id: "records",
    name: "Structured records",
    klass: "tiled",
    blurb: "Almost-identical JSON objects. The kind of state an agent actually writes down.",
    text: RECORDS,
  },
  {
    id: "code",
    name: "Source code",
    klass: "natural",
    blurb: "A function copy-pasted. Sharing should collapse the copies without losing the shape.",
    text: CODE_SNIPPET,
  },
  {
    id: "english",
    name: "Natural language",
    klass: "natural",
    blurb: "Prose has Zipf structure, not tiles. Modest density, not a miracle.",
    text: ENGLISH,
  },
  {
    id: "dna",
    name: "Tandem DNA",
    klass: "tiled",
    blurb: "Short tandem repeats with a mutation in the middle — biology’s version of the same law.",
    text: DNA,
  },
  {
    id: "random",
    name: "Incompressible",
    klass: "random",
    blurb: "A seeded pseudo-random string. Anything claiming D ≫ 1 here is overfitting.",
    text: lcg(20260910, 180, "abcdefghijklmnopqrstuvwxyz"),
  },
];

export const CORPUS_BY_ID: Record<string, Corpus> = Object.fromEntries(
  CORPORA.map((c) => [c.id, c]),
);

export const CLASS_LABEL: Record<StructureClass, string> = {
  tiled: "Tiled",
  nested: "Nested",
  morphic: "Morphic",
  natural: "Natural",
  random: "Random",
};
