/**
 * Phase 2 protocol — frozen 2026-09-10.
 *
 * Not a runner. A specification. C is no longer string length.
 * No experiment has been executed under this protocol.
 */

export const PHASE2_STATUS = "frozen" as const;
export const PHASE2_FROZEN_ON = "2026-09-10";

export const QUESTION =
  "How much capability can a system reconstruct per persistent bit, at what reconstruction cost?";

export const OBJECTIVE = {
  maximize: "C / S",
  subjectTo: "K ≤ K_max",
} as const;

export const AXES = [
  {
    id: "S",
    name: "State",
    def: "Persistent bits that remain after reconstruction. Not the runtime. Not the output.",
  },
  {
    id: "K",
    name: "Reconstruction",
    def: "Work to produce the capability from state, on this query, under convention K3 (Thermo).",
  },
  {
    id: "C",
    name: "Capability",
    def: "Functional success on held-out queries. Not n. Not |expand(G)|. A count of correct answers.",
  },
] as const;

export const ACCOUNTING: { where: string; countsAs: "state" | "cost" | "infrastructure" }[] = [
  { where: "weights, parameters, stored tables", countsAs: "state" },
  { where: "the persistent grammar or program", countsAs: "state" },
  { where: "a frozen prompt, seed, or cache kept between queries", countsAs: "state" },
  { where: "environment facts the method is allowed to reread", countsAs: "state" },
  { where: "eval steps, rewrites, lattice generations", countsAs: "cost" },
  { where: "writing the answer (Landauer floor)", countsAs: "cost" },
  { where: "a general expander / JS runtime shared by every method", countsAs: "infrastructure" },
  { where: "a task-specific interpreter or decoder", countsAs: "state" },
];

export const BASELINES = [
  {
    id: "B0",
    name: "Direct store",
    how: "Capability is the table. S = |table|. K ≈ 0. Density ceiling = 1 if C counts rows stored.",
  },
  {
    id: "B1",
    name: "Compress the table",
    how: "Store a compressed table, decompress on query. Phase 1 B1. Wins on S, pays K.",
  },
  {
    id: "B2",
    name: "Generate",
    how: "A grammar or program that produces answers. S = |G|. This is Law, now scored on C not n.",
  },
  {
    id: "B3",
    name: "Targeted reconstruction",
    how: "From minimal state and the request, rebuild only the capability asked for. Not the whole table.",
  },
] as const;

export const LADDER = [
  { level: 0, name: "Generative traces", exam: "Koch, tiles, Rule 90. Instrument calibration. Cannot win." },
  { level: 1, name: "Functions", exam: "F1. A total function on a finite query set. First real exam." },
  { level: 2, name: "Function families", exam: "One state, many related functions. Sharing must be shown, not assumed." },
  { level: 3, name: "Composable tasks", exam: "Answers that chain. Reconstruction of a part, not the closure." },
  { level: 4, name: "Novel capability", exam: "A query outside the training pairs, still correct, still accounted." },
  { level: 5, name: "A living system", exam: "Agent, model, or store. Own annex. Not this file." },
] as const;

export const F1 = {
  id: "F1",
  name: "Reconstruct a function",
  object:
    "A total function f on strings, exhibited as a finite set of training pairs Q_train and a disjoint held-out set Q_test generated by the same rule.",
  S: "Symbol-count |G| of the persistent artifact (Phase 1 unit). Also report UTF-8 bytes. Primary is |G|.",
  C: "|{ x ∈ Q_test : reconstruct(A, x) = f(x) }|. Correct answers, not concatenated length.",
  K: "K3. SLP: |G|. Iterative generator: Σ rewrite lengths. Decoder: steps to emit the answer.",
  kMax: "Fixed before the run. A method that exceeds K_max on a query scores 0 on that query.",
  negativeControl:
    "A Q_test of incompressible random pairs. C must not beat B0 by storing luck. Same spirit as Phase 1 random.",
  pass: "On a structured f: some method has C/S > 1.02 × (C/S)_B0, every query K ≤ K_max, C ≥ 0.9 |Q_test|, reconstruction checked, negative control sane (C/S ≲ B0).",
  kill: "Q_test leaked into A. Interpreter specialized to f and not counted. Win vanishes when bytes are the unit. Identity of answers unchecked.",
} as const;

export const CERTIFICATE = [
  "hash of artifact A",
  "protocol version (this file's date)",
  "function family / generator seed",
  "Q_train size, Q_test size (the tests themselves are public)",
  "S, C, K_max, K per query",
  "baseline scores B0–B3",
  "negative-control row",
  "verdict PASS | MIXED | FAIL | kill",
] as const;

export const KILL = [
  "C defined as n, or as a hash, or as a model grade.",
  "A bit of information needed for a query is not in S, not in K, not in infrastructure.",
  "The method reads Q_test.",
  "Criteria changed after seeing the number.",
  "Level 0 (Koch, Sierpiński) offered as a win.",
] as const;

export function specIsFrozen(): boolean {
  return PHASE2_STATUS === "frozen";
}

export function cIsNotLength(): boolean {
  return !F1.C.includes("|expand") && F1.C.includes("Q_test");
}
